/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

import categorias.VentanaFrutas;
import categorias.VentanaVerduras;

/**
 *
 * @author jquesadaabeijon
 */
public class VentanaPrincipal extends javax.swing.JFrame {

//    int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
//    int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();

//        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
//        this.setSize((int) d.getWidth(), (int) d.getHeight());
//        panelfondo.setSize((int) d.getWidth(), (int) d.getHeight());
//        
//        this.setBounds((d.width / 2) - (this.getWidth() / 2), (d.height / 2) - (this.getHeight() / 2), 1366, 768);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelfondo = new javax.swing.JPanel();
        btBeb = new javax.swing.JButton();
        btCer = new javax.swing.JButton();
        btAce = new javax.swing.JButton();
        btHort = new javax.swing.JButton();
        btFrutas = new javax.swing.JButton();
        btLact = new javax.swing.JButton();
        btCarn = new javax.swing.JButton();
        btPan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MercaTerra - Venta de productos agrícolas y/o ecológicos");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1366, 720));
        setPreferredSize(new java.awt.Dimension(1366, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelfondo.setBackground(new java.awt.Color(255, 255, 255));
        panelfondo.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 51)), new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 1, true)));
        panelfondo.setMaximumSize(new java.awt.Dimension(1366, 768));
        panelfondo.setLayout(null);

        btBeb.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        btBeb.setForeground(new java.awt.Color(255, 255, 255));
        btBeb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bebidas.jpeg"))); // NOI18N
        btBeb.setText("BEBIDAS");
        btBeb.setContentAreaFilled(false);
        btBeb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btBeb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btBeb.setMaximumSize(new java.awt.Dimension(220, 150));
        btBeb.setMinimumSize(new java.awt.Dimension(220, 150));
        btBeb.setPreferredSize(new java.awt.Dimension(220, 150));
        btBeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBebActionPerformed(evt);
            }
        });
        panelfondo.add(btBeb);
        btBeb.setBounds(1060, 490, 250, 170);
        btBeb.getAccessibleContext().setAccessibleParent(this);

        btCer.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        btCer.setForeground(new java.awt.Color(255, 255, 255));
        btCer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cereales.jpeg"))); // NOI18N
        btCer.setText("<html><p align=\"center\">CEREALES Y LEGUMBRES</p></html>");
        btCer.setContentAreaFilled(false);
        btCer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCer.setMaximumSize(new java.awt.Dimension(290, 250));
        btCer.setMinimumSize(new java.awt.Dimension(290, 250));
        btCer.setPreferredSize(new java.awt.Dimension(220, 150));
        btCer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCerActionPerformed(evt);
            }
        });
        panelfondo.add(btCer);
        btCer.setBounds(730, 240, 250, 170);

        btAce.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        btAce.setForeground(new java.awt.Color(255, 255, 255));
        btAce.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aceites.jpeg"))); // NOI18N
        btAce.setText("ACEITES");
        btAce.setContentAreaFilled(false);
        btAce.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAce.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAce.setMaximumSize(new java.awt.Dimension(220, 150));
        btAce.setMinimumSize(new java.awt.Dimension(220, 150));
        btAce.setPreferredSize(new java.awt.Dimension(220, 150));
        btAce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceActionPerformed(evt);
            }
        });
        panelfondo.add(btAce);
        btAce.setBounds(730, 490, 250, 170);

        btHort.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        btHort.setForeground(new java.awt.Color(255, 255, 255));
        btHort.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hortalizas.jpg"))); // NOI18N
        btHort.setText("<html><p align=\"center\">VERDURAS Y HORTALIZAS</p></html>");
        btHort.setActionCommand("<html><p>VERDURAS</p><p>Y</p><p>HORTALIZAS</p></html>");
        btHort.setAutoscrolls(true);
        btHort.setContentAreaFilled(false);
        btHort.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btHort.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btHort.setMaximumSize(new java.awt.Dimension(220, 150));
        btHort.setMinimumSize(new java.awt.Dimension(220, 150));
        btHort.setPreferredSize(new java.awt.Dimension(220, 150));
        btHort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHortActionPerformed(evt);
            }
        });
        panelfondo.add(btHort);
        btHort.setBounds(390, 240, 250, 170);

        btFrutas.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        btFrutas.setForeground(new java.awt.Color(255, 255, 255));
        btFrutas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/frutas.jpg"))); // NOI18N
        btFrutas.setText("FRUTAS");
        btFrutas.setToolTipText("");
        btFrutas.setContentAreaFilled(false);
        btFrutas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btFrutas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFrutas.setMaximumSize(new java.awt.Dimension(290, 250));
        btFrutas.setMinimumSize(new java.awt.Dimension(290, 250));
        btFrutas.setPreferredSize(new java.awt.Dimension(250, 180));
        btFrutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFrutasActionPerformed(evt);
            }
        });
        panelfondo.add(btFrutas);
        btFrutas.setBounds(50, 240, 250, 170);

        btLact.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        btLact.setForeground(new java.awt.Color(255, 255, 255));
        btLact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lacteos.jpeg"))); // NOI18N
        btLact.setText("LÁCTEOS");
        btLact.setContentAreaFilled(false);
        btLact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLact.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLact.setMaximumSize(new java.awt.Dimension(290, 250));
        btLact.setMinimumSize(new java.awt.Dimension(290, 250));
        btLact.setPreferredSize(new java.awt.Dimension(220, 150));
        btLact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLactActionPerformed(evt);
            }
        });
        panelfondo.add(btLact);
        btLact.setBounds(390, 490, 250, 170);

        btCarn.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        btCarn.setForeground(new java.awt.Color(255, 255, 255));
        btCarn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carnes.jpg"))); // NOI18N
        btCarn.setText("CARNES");
        btCarn.setContentAreaFilled(false);
        btCarn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCarn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCarn.setMaximumSize(new java.awt.Dimension(220, 150));
        btCarn.setMinimumSize(new java.awt.Dimension(220, 150));
        btCarn.setPreferredSize(new java.awt.Dimension(220, 150));
        btCarn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCarnActionPerformed(evt);
            }
        });
        panelfondo.add(btCarn);
        btCarn.setBounds(1060, 240, 250, 170);

        btPan.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        btPan.setForeground(new java.awt.Color(255, 255, 255));
        btPan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/panaderia.jpeg"))); // NOI18N
        btPan.setText("PANADERÍA");
        btPan.setContentAreaFilled(false);
        btPan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPan.setMaximumSize(new java.awt.Dimension(290, 250));
        btPan.setMinimumSize(new java.awt.Dimension(290, 250));
        btPan.setPreferredSize(new java.awt.Dimension(220, 150));
        btPan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPanActionPerformed(evt);
            }
        });
        panelfondo.add(btPan);
        btPan.setBounds(50, 490, 250, 170);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo1.png"))); // NOI18N
        panelfondo.add(jLabel1);
        jLabel1.setBounds(540, 20, 290, 200);

        titulo.setFont(new java.awt.Font("Century Schoolbook L", 1, 36)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/principal1.jpg"))); // NOI18N
        titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelfondo.add(titulo);
        titulo.setBounds(0, 0, 1440, 900);

        getContentPane().add(panelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBebActionPerformed


    }//GEN-LAST:event_btBebActionPerformed

    private void btCerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCerActionPerformed


    }//GEN-LAST:event_btCerActionPerformed

    private void btAceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceActionPerformed


    }//GEN-LAST:event_btAceActionPerformed

    private void btHortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHortActionPerformed

        VentanaVerduras hort = new VentanaVerduras();
        hort.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btHortActionPerformed

    private void btFrutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFrutasActionPerformed

        VentanaFrutas frut = new VentanaFrutas();
        frut.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btFrutasActionPerformed

    private void btLactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLactActionPerformed

    private void btCarnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCarnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCarnActionPerformed

    private void btPanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btPanActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//        new VentanaPrincipal();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAce;
    private javax.swing.JButton btBeb;
    private javax.swing.JButton btCarn;
    private javax.swing.JButton btCer;
    private javax.swing.JButton btFrutas;
    private javax.swing.JButton btHort;
    private javax.swing.JButton btLact;
    private javax.swing.JButton btPan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelfondo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
        }
                


