/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agripro;

import java.awt.Dimension;
import java.awt.Toolkit;


/**
 *
 * @author jquesadaabeijon
 */
public class VentanaPrincipal extends javax.swing.JFrame {

//    int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
//    int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();

//        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
//        this.setSize((int) d.getWidth(), (int) d.getHeight());
//        panelfondo.setSize((int) d.getWidth(), (int) d.getHeight());
//        
//        this.setBounds((d.width / 2) - (this.getWidth() / 2), (d.height / 2) - (this.getHeight() / 2), 1366, 768);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelfondo = new javax.swing.JPanel();
        btBebidas = new javax.swing.JButton();
        btFrut = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        btCarne = new javax.swing.JButton();
        btHort = new javax.swing.JButton();
        btFrut1 = new javax.swing.JButton();
        btFrut2 = new javax.swing.JButton();
        btCarne1 = new javax.swing.JButton();
        btFrut3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AgriPro - Venta de productos agrícolas y/o ecológicos");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelfondo.setBackground(new java.awt.Color(255, 255, 255));
        panelfondo.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 51)), new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 1, true)));
        panelfondo.setMaximumSize(new java.awt.Dimension(1366, 768));

        btBebidas.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        btBebidas.setForeground(new java.awt.Color(255, 255, 255));
        btBebidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bebidas.jpeg"))); // NOI18N
        btBebidas.setText("BEBIDAS");
        btBebidas.setContentAreaFilled(false);
        btBebidas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btBebidas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btBebidas.setMaximumSize(new java.awt.Dimension(220, 150));
        btBebidas.setMinimumSize(new java.awt.Dimension(220, 150));
        btBebidas.setPreferredSize(new java.awt.Dimension(220, 150));
        btBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBebidasActionPerformed(evt);
            }
        });

        btFrut.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        btFrut.setForeground(new java.awt.Color(255, 255, 255));
        btFrut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cereales.jpeg"))); // NOI18N
        btFrut.setText("<html><p>CEREALES Y LEGUMBRES</p></html>");
        btFrut.setContentAreaFilled(false);
        btFrut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btFrut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFrut.setMaximumSize(new java.awt.Dimension(290, 250));
        btFrut.setMinimumSize(new java.awt.Dimension(290, 250));
        btFrut.setPreferredSize(new java.awt.Dimension(220, 150));
        btFrut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFrutActionPerformed(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Century Schoolbook L", 1, 36)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("CATEGORÍAS");
        titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btCarne.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        btCarne.setForeground(new java.awt.Color(255, 255, 255));
        btCarne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aceites.jpeg"))); // NOI18N
        btCarne.setText("ACEITES");
        btCarne.setContentAreaFilled(false);
        btCarne.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCarne.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCarne.setMaximumSize(new java.awt.Dimension(220, 150));
        btCarne.setMinimumSize(new java.awt.Dimension(220, 150));
        btCarne.setPreferredSize(new java.awt.Dimension(220, 150));
        btCarne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCarneActionPerformed(evt);
            }
        });

        btHort.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        btHort.setForeground(new java.awt.Color(255, 255, 255));
        btHort.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hortalizas.jpg"))); // NOI18N
        btHort.setText("<html><p>VERDURAS Y HORTALIZAS</p></html>");
        btHort.setActionCommand("<html><p>VERDURAS Y HORTALIZAS</p></html>");
        btHort.setAutoscrolls(true);
        btHort.setContentAreaFilled(false);
        btHort.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btHort.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btHort.setMaximumSize(new java.awt.Dimension(220, 150));
        btHort.setMinimumSize(new java.awt.Dimension(220, 150));
        btHort.setPreferredSize(new java.awt.Dimension(220, 150));
        btHort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHortActionPerformed(evt);
            }
        });

        btFrut1.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        btFrut1.setForeground(new java.awt.Color(255, 255, 255));
        btFrut1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/frutas.jpg"))); // NOI18N
        btFrut1.setText("FRUTAS");
        btFrut1.setContentAreaFilled(false);
        btFrut1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btFrut1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFrut1.setMaximumSize(new java.awt.Dimension(290, 250));
        btFrut1.setMinimumSize(new java.awt.Dimension(290, 250));
        btFrut1.setPreferredSize(new java.awt.Dimension(250, 180));
        btFrut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFrut1ActionPerformed(evt);
            }
        });

        btFrut2.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        btFrut2.setForeground(new java.awt.Color(255, 255, 255));
        btFrut2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lacteos.jpeg"))); // NOI18N
        btFrut2.setText("LÁCTEOS");
        btFrut2.setContentAreaFilled(false);
        btFrut2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btFrut2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFrut2.setMaximumSize(new java.awt.Dimension(290, 250));
        btFrut2.setMinimumSize(new java.awt.Dimension(290, 250));
        btFrut2.setPreferredSize(new java.awt.Dimension(220, 150));
        btFrut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFrut2ActionPerformed(evt);
            }
        });

        btCarne1.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        btCarne1.setForeground(new java.awt.Color(255, 255, 255));
        btCarne1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carnes.jpg"))); // NOI18N
        btCarne1.setText("CARNES");
        btCarne1.setContentAreaFilled(false);
        btCarne1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCarne1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCarne1.setMaximumSize(new java.awt.Dimension(220, 150));
        btCarne1.setMinimumSize(new java.awt.Dimension(220, 150));
        btCarne1.setPreferredSize(new java.awt.Dimension(220, 150));
        btCarne1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCarne1ActionPerformed(evt);
            }
        });

        btFrut3.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        btFrut3.setForeground(new java.awt.Color(255, 255, 255));
        btFrut3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/panaderia.jpeg"))); // NOI18N
        btFrut3.setText("PANADERÍA");
        btFrut3.setContentAreaFilled(false);
        btFrut3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btFrut3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFrut3.setMaximumSize(new java.awt.Dimension(290, 250));
        btFrut3.setMinimumSize(new java.awt.Dimension(290, 250));
        btFrut3.setPreferredSize(new java.awt.Dimension(220, 150));
        btFrut3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFrut3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelfondoLayout = new javax.swing.GroupLayout(panelfondo);
        panelfondo.setLayout(panelfondoLayout);
        panelfondoLayout.setHorizontalGroup(
            panelfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfondoLayout.createSequentialGroup()
                .addGroup(panelfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelfondoLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(panelfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btFrut3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btFrut1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86)
                        .addGroup(panelfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btHort, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btFrut2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(108, 108, 108)
                        .addGroup(panelfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btFrut, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btCarne, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79)
                        .addGroup(panelfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btCarne1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelfondoLayout.createSequentialGroup()
                        .addGap(541, 541, 541)
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(237, 237, 237))
        );
        panelfondoLayout.setVerticalGroup(
            panelfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(panelfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btCarne1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btFrut1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelfondoLayout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(panelfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btHort, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btFrut, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(panelfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCarne, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btFrut2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btFrut3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(236, 236, 236))
        );

        btBebidas.getAccessibleContext().setAccessibleParent(this);

        getContentPane().add(panelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBebidasActionPerformed
        
        
        
    }//GEN-LAST:event_btBebidasActionPerformed

    private void btFrutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFrutActionPerformed
        
        VentanaFrutas frut = new VentanaFrutas();
        frut.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btFrutActionPerformed

    private void btCarneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCarneActionPerformed

        
        
    }//GEN-LAST:event_btCarneActionPerformed

    private void btHortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHortActionPerformed
        
        VentanaVerduras hort = new VentanaVerduras();
        hort.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btHortActionPerformed

    private void btFrut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFrut1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btFrut1ActionPerformed

    private void btFrut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFrut2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btFrut2ActionPerformed

    private void btCarne1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCarne1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCarne1ActionPerformed

    private void btFrut3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFrut3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btFrut3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//        new VentanaPrincipal();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBebidas;
    private javax.swing.JButton btCarne;
    private javax.swing.JButton btCarne1;
    private javax.swing.JButton btFrut;
    private javax.swing.JButton btFrut1;
    private javax.swing.JButton btFrut2;
    private javax.swing.JButton btFrut3;
    private javax.swing.JButton btHort;
    private javax.swing.JPanel panelfondo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
