/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agripro;

import java.awt.Dimension;
import java.awt.Toolkit;


/**
 *
 * @author jquesadaabeijon
 */
public class VentanaPrincipal extends javax.swing.JFrame {

//    int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
//    int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();

        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize((int) d.getWidth(), (int) d.getHeight());
        panelfondo.setSize((int) d.getWidth(), (int) d.getHeight());
        
        this.setBounds((d.width / 2) - (this.getWidth() / 2), (d.height / 2) - (this.getHeight() / 2), 1366, 768);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelfondo = new javax.swing.JPanel();
        btHort = new javax.swing.JButton();
        btFrut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AgriPro - Venta de productos agrícolas y/o ecológicos");
        setBackground(new java.awt.Color(255, 51, 0));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelfondo.setBackground(new java.awt.Color(51, 102, 0));
        panelfondo.setLayout(null);

        btHort.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        btHort.setForeground(new java.awt.Color(255, 255, 255));
        btHort.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agripro/hortalizas.jpg"))); // NOI18N
        btHort.setText("HORTALIZAS");
        btHort.setContentAreaFilled(false);
        btHort.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btHort.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btHort.setMaximumSize(new java.awt.Dimension(220, 150));
        btHort.setMinimumSize(new java.awt.Dimension(220, 150));
        btHort.setPreferredSize(new java.awt.Dimension(220, 150));
        btHort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHortActionPerformed(evt);
            }
        });
        panelfondo.add(btHort);
        btHort.setBounds(300, 90, 220, 150);
        btHort.getAccessibleContext().setAccessibleParent(this);

        btFrut.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        btFrut.setForeground(new java.awt.Color(255, 255, 255));
        btFrut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agripro/frutas.jpg"))); // NOI18N
        btFrut.setText("FRUTAS");
        btFrut.setContentAreaFilled(false);
        btFrut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btFrut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFrut.setMaximumSize(new java.awt.Dimension(290, 250));
        btFrut.setMinimumSize(new java.awt.Dimension(290, 250));
        btFrut.setPreferredSize(new java.awt.Dimension(220, 150));
        panelfondo.add(btFrut);
        btFrut.setBounds(40, 90, 220, 150);

        getContentPane().add(panelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btHortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btHortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//        new VentanaPrincipal();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFrut;
    private javax.swing.JButton btHort;
    private javax.swing.JPanel panelfondo;
    // End of variables declaration//GEN-END:variables
}
